### ISSUE TITLE
Can't load the image

### ISSUE THREAD

**Issue by Ar57m** [MaidFoundation/Maid#109]
![Screenshot_20231114_094710](https://github.com/MaidFoundation/Maid/assets/132871733/434c0055-1648-48da-b8d5-b4885e6d3cdc)
![Screenshot_20231114_094642](https://github.com/MaidFoundation/Maid/assets/132871733/18c75799-abf1-4598-a937-7c43640b0241)

**Comment by sfiannaca** [comment]
There is another little bug if u tap on Save Image and no image is already loaded

**Comment by danemadsen** [comment]
@Ar57m @sfiannaca Please check if the latest release resolves both your issues

**Comment by Ar57m** [comment]
> @Ar57m @sfiannaca Please check if the latest release resolves both your issues

for me it's working fine now, saving and loading the image with all the character info.

**Comment by sfiannaca** [comment]
> @Ar57m @sfiannaca Please check if the latest release resolves both your issues

yeah both are fixed
