### ISSUE TITLE
app not installed

### ISSUE THREAD

**Issue by thesanju** [MaidFoundation/Maid#133]
getting "app not installed" on android version 10.

**Comment by danemadsen** [comment]
Ok, how are you getting this issue? When trying to install the APK or when trying to launch?

**Comment by thesanju** [comment]
while trying to install the APK, and I tried on my friends phone it installed and setup ollama in remote but not working.

**Comment by danemadsen** [comment]
ok, it might be because im targeting a newer version of the android sdk. I'll look into it

**Comment by moh21amed** [comment]
This problem is common when you don't have enough space on your phone, make sure you have at least 2gb free space and try again

**Comment by thesanju** [comment]
Yeah that's what I thought, but it's working on my friends phone he has 6 gig memory, thank you.
