### ISSUE TITLE
Error loading file

### ISSUE THREAD

**Issue by moh21amed** [MaidFoundation/Maid#135]
Just after i press load model i get error loading file and empty modal path withou even opening file picker , storage permission are granted
![Screenshot_20231122-024934](https://github.com/MaidFoundation/Maid/assets/20410493/b772bb8b-14de-435e-a1c5-ff2be556b1ef)
![Screenshot_20231122-024938](https://github.com/MaidFoundation/Maid/assets/20410493/e4382e26-1edd-4e79-8a74-8a0c32af0a0d)

**Comment by danemadsen** [comment]
What version of android are you using? As with #133 it sounds like we have an issue with older versions of android

**Comment by danemadsen** [comment]
Give the apk here https://github.com/MaidFoundation/Maid/actions/runs/6956034240 a try

It should be fixed

**Comment by moh21amed** [comment]
I am using Android 10
After installing the recommended apk now the model loads but i after i type the prompt it loads for about 5 seconds then it crashes, but i think it is due to low device ram (3gb) inspite of i am using tinyllama 3b q4 which should use small ram

**Comment by danemadsen** [comment]
Yeah that sounds like normal behavior now, Minimum ram for running local models on a phone is 8GB. Just because the phone has 3gb of ram doent mean that full 3GB of ram is usable by maid as much of that 3GB will already be provisioned by the system and potentially other apps.
