### ISSUE TITLE
Storage permission

### ISSUE THREAD

**Issue by sfiannaca** [MaidFoundation/maid#140]
In a clean installation (API 33 and API 34), not all permissions are requested. 
As a result, when the file manager opens, only folders are visible

Maybe it come from this line:
https://github.com/MaidFoundation/maid/blob/a03e9bacd54db76a0472566b13bc49332ae23edc/lib/static/file_manager.dart#L13

**Comment by danemadsen** [comment]
Ok i've fixed this now.

**Comment by ElmorenohWTF** [comment]
This keeps happening to me, I can't find a way to upload a gguf model, I just don't see files, only folders.

**Comment by danemadsen** [comment]
Sounds like an issue I thought we fixed. Open a issue explaining what platform you're using and how to reproduce it and I'll have a look at it for you.

With regards,
Dane Madsen
________________________________
