### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by sfiannaca** [MaidFoundation/maid#153]
I noticed that when a user attempts to run the app with a local unsupported model, even if the device has enough ram, the app tries to generate something and subsequently crashes. 

I suggest implementing error handling at a low level to address this issue. 

llama.cpp already handled it, so it should be simple to fix

**Comment by danemadsen** [comment]
You mean if a user attempts to run a model too large for their devices ram? Generally i like operating on the idea that no hard restrictions are placed on running models. If the user wants to attempt to run a model that needs more ram than they have, I will let them but yeah it will most likely crash.

Instead I would prefer to implement a warning for such models, or if you wanted to implement some logic to prevent the user from running such models, I would need a way to toggle it off in the settings page.

**Comment by sfiannaca** [comment]
Yeah I like your idea

I mean
If a user attempts to load a fake or corrupt .gguf file or a model that fits into RAM but is not officially supported by llama.ccp yet 
or is using an outdated version.
