### ISSUE TITLE
[Android] not able to set remote model from dropdown

### ISSUE THREAD

**Issue by krissz22** [MaidFoundation/maid#165]
Xiaomi Mi 10 Lite 
Android 12

![Screenshot_2023-11-29-11-37-46-692_com.danemadsen.maid.jpg](https://github.com/MaidFoundation/maid/assets/146206294/5651b363-d8c9-4a38-bbf7-96969e4227a9)

**Comment by danemadsen** [comment]
That generally means your ollama server isn't setup correctly, or you dont have any models pulled into ollama.

**Comment by krissz22** [comment]
Although I can query Ollama running on the same server from another PC on the local network? This configuration runs smoothly.

**Comment by gvalson** [comment]
@krissz22 try running ollama with these settings:

`OLLAMA_HOST=0.0.0.0:11434 OLLAMA_ORIGINS=[YOUR PHONE'S IP ADDRESS]:* ollama serve`

You can see more about these variables in the [FAQ document](https://github.com/jmorganca/ollama/blob/main/docs/faq.md#how-can-i-expose-ollama-on-my-network).

**Comment by taozhiyuai** [comment]
mobile and laptop where ollama is installed are all in the same LAN. I set IP:11434 on mobile. can not work.
