### ISSUE TITLE
Question: preprompt same as system message?

### ISSUE THREAD

**Issue by GameOverFlowChart** [MaidFoundation/maid#193]
As the title says, I want to set a system message but I'm not sure. I like the raw input field of gpt4all, character cards are a bit cryptic to me.

Actually, I need ChatML for openhermes.

I also don't know if I need to indicate the new line after user or if that's added automatically.

Well forget everything above and let's change this to a bug report because the preprompt can't be even changed, even saving the json, editing it manually and loading it again won't work. And there isn't a workaround because the maid prepomt is automatically added as soon as you create a new character, so there is no way of getting rid of it.

**Comment by danemadsen** [comment]
Yeah pre-prompt is the same as system message.
Ill get around to ChatML at some point
The new line is added automatically
Ill look into your issue with character card preprompts

**Comment by GameOverFlowChart** [comment]
> @GameOverFlowChart Ok when this build completes give it a shot and see if your issue is fixed?
> 
> https://github.com/MaidFoundation/maid/actions/runs/7115145566

Yes, this worked. It seems like the json import still doesn't change that field (or I edited the json wrong) but I can simply change that field in the app and even turn it empty. And I tested it by asking the model if it's a maid. The answer was no.
