### ISSUE TITLE
Image not saved

### ISSUE THREAD

**Issue by GameOverFlowChart** [MaidFoundation/maid#196]
I guess this is a known missing feature but once the app is closed the image for the character is gone. The app should save a copy in it's internal memory.

**Comment by danemadsen** [comment]
ok give the build here a go

https://github.com/MaidFoundation/maid/actions/runs/7141484360

the issue should be fixed now

**Comment by GameOverFlowChart** [comment]
I got a notification from GitHub for this issue but I don't see why.

**Comment by danemadsen** [comment]
I acciendtly commented here when I ment to comment on #200, so I removed it 😅
