### ISSUE TITLE
App crash when running certain 1B models

### ISSUE THREAD

**Issue by RookieIndieDev** [MaidFoundation/maid#197]
Running Maid on Moto G9 Android 11. Tried to run two 1B models obtained from Hugging face [this one](https://huggingface.co/TheBloke/Tinyllama-2-1b-miniguanaco-GGUF) and another one. The model is loaded successfully but when submitting a prompt the app crashes. Running it locally. Another 3B model works fine but 1B that I have tried so far crashes on my device.

**Comment by RookieIndieDev** [comment]
> I could be wrong but i think that models a GGUFV1 model which llama.cpp dropped about a month ago. Ive been trying to keep the functionality working but its pretty unstable

Oh. Which version of GGUF is compatible currently?

**Comment by danemadsen** [comment]
> > I could be wrong but i think that models a GGUFV1 model which llama.cpp dropped about a month ago. Ive been trying to keep the functionality working but its pretty unstable
> 
> Oh. Which version of GGUF is compatible currently? 

Well both are ment to be compatible but sometime v1 models can cause issues.

Give the latest actions build a try, your issue might be fixed

**Comment by danemadsen** [comment]
@RookieIndieDev This build should work:

https://github.com/MaidFoundation/maid/actions/runs/7127583201

**Comment by RookieIndieDev** [comment]
@danemadsen Is the release published on github? Can't seem to get the files from the action artifacts.

**Comment by RookieIndieDev** [comment]
The issue is resolved. Some models do crash still. The tinyllama-2-1b-miniguanaco.Q2K_K crashes but Q3_K_L doesn't. I'll close the issue, might be an issue with the model itself. Might be an even older version of GGUF for that specific one.

**Comment by danemadsen** [comment]
there seems to be a lot wrong with my implementation of llama.cpp at the moment. Ill be rewriting it in the future but that's why certain models don't work.

this issue was effectively a duplicate of #185 so you're free to close it and discuss anything further in that issue
