### ISSUE TITLE
Saving Character (bug)

### ISSUE THREAD

**Issue by GameOverFlowChart** [MaidFoundation/maid#202]
Does saving the character image really encode the character informations into the png? If so that's really cool. But...  it seems to have a problem with emojis inside the preprompt. So that needs a fix unfortunately.

**Comment by danemadsen** [comment]
Yes it does, it saves the character card into the PNG's metadata. Its not true steganography so the data isnt encrypted but it works for making the data transportable. If we need emojii support we will have to create a more complex encoding method

**Comment by GameOverFlowChart** [comment]
> Ok im looking at it now, can you please tell me what issue you're having with emojis? Are they not encoding correctly or something?

Uhm it's not a top priority issue it's not a problem for me if it takes time to be solved.
The problem is that if the system prompt contains Emojis and you want to save image you get the following error pop up: Error: Invalid argument (string): Contains invalid characters.: "<the system prompt>" and the image isn't saved.

**Comment by danemadsen** [comment]
> > Ok im looking at it now, can you please tell me what issue you're having with emojis? Are they not encoding correctly or something?
> 
> Uhm it's not a top priority issue it's not a problem for me if it takes time to be solved.
> The problem is that if the system prompt contains Emojis and you want to save image you get the following error pop up: Error: Invalid argument (string): Contains invalid characters.: "//the system prompt" and the image isn't saved.

Ok, I had a quick look and its probably due to the characters not being encoded into Utf8

**Comment by danemadsen** [comment]
Ok, I looked into it and this is actually an issue with the image package of flutter so not something i can fix in maid unfortunately.

If you want you can open up an issue in the image packages repo:

https://pub.dev/packages/image

**Comment by danemadsen** [comment]
There is a way i can do it but it would mean encoding all the data in a very unreadable way which would make the format less open and usable by other software
