### ISSUE TITLE
(Maybe Not) Android V1.0.6 Broken

### ISSUE THREAD

**Issue by alxspiker** [MaidFoundation/Maid#59]
Just updated, was working on last update. Attached screenshots. Also clicking those two new buttons on the chat screen just crashes the app as well. Cleared cache and data, and tried a different model as well.

![Screenshot_20231104_230732.png](https://github.com/MaidFoundation/Maid/assets/7357054/801c9d0f-b8dc-46cc-938a-cb1a80261fee)

![Screenshot_20231104_230738.png](https://github.com/MaidFoundation/Maid/assets/7357054/f8a2d5de-dec0-4d3f-ae6d-0005d88a6676)

![Screenshot_20231104_230752.jpg](https://github.com/MaidFoundation/Maid/assets/7357054/edc1da32-cf92-471e-ba9d-216845705964)

**Comment by alxspiker** [comment]
![Screenshot_20231104_232424.png](https://github.com/MaidFoundation/Maid/assets/7357054/b531bd0e-2ea6-4de8-a5fe-2699c1dce2c8)

Started working again, I'll try to load my characters again.

**Comment by alxspiker** [comment]
# Fixed! Not sure what it was, but I cleared the cache and data multiple times before it started to work and not crash.

![Screenshot_20231104_232919.png](https://github.com/MaidFoundation/Maid/assets/7357054/b15c31d6-7b65-4f54-a2c0-b739ef102f84)

Also new features work but I don't get what the edit button does, it didn't allow me to enter any text and won't let me submit new text and it just loads forever:
![Screenshot_20231104_232938.png](https://github.com/MaidFoundation/Maid/assets/7357054/68e9e3c3-ef3d-48e5-9485-a484221ec808)

**Comment by danemadsen** [comment]
Yeah ive experienced this issue too, not sure what causes it

**Comment by danemadsen** [comment]
The edit button waits for you to type a message and hit enter like you would normally
